openapi: 3.0.1
info:
  title: Search Plugin
  description: A plugin that searches for information needed to respond to the user, phrased as {query}.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /search/quick/{query}:
    get:
      operationId: quicksearch
      summary: a search optimized for speed of response with a moderate number results.
      parameters:
      - in: path
        name: query
        schema:
            type: string
        required: true
        description: phrase describing the information needed.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getSearchResponse'

  /search/full/{query}:
    get:
      operationId: fullsearch
      summary: a search optimized for maximum number of results while trying to stay within chatgpt timing. this entrypoint may timeout, and may offer quicker or more complete response if a search request is repeated
      parameters:
      - in: path
        name: query
        schema:
            type: string
        required: true
        description: phrase describing the information needed.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getSearchResponse'

components:
  schemas:
    getSearchResponse:
      type: object
      properties:
        response:
          type: array
          items:
            type: json
          description: list of information found.
